name: bloom_mama
description: Приложение для беременных — напоминания, шевеления, схватки, вода, вес и таймлайн.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_local_notifications: ^19.4.1
  permission_handler: ^12.0.1
  timezone: ^0.10.1
  intl: ^0.20.2
  path_provider: ^2.1.5
  file_picker: ^10.3.2
  go_router: ^16.2.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/pregnancy_weeks.json
    - assets/checklists.json
    